name: Frontend CI

on:
  pull_request:
    branches: [ main ]
    paths: 
      - "client/build/**"
      - ".github/workflows/client.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm run client-ci
        npm run client-build
