name: Frontend CI & CD

on:
  push:
    branches: [ main ]
    paths:
      - "client/**"
      - ".github/workflows/client.yml"
      - ".github/workflows/client-beta.yml"
      - ".github/workflows/client-pull.yml"

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean Installing Dependencies
      run: npm run ci:client
    - name: Running tests
      run: npm run test:client:auto
    - name: Building
      run: npm run build:client
    - name: Firebase Frontend Live Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONVAMEET }}'
        projectId: convameet
        entryPoint: "./client"
        channelId: live
