name: Backend CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - "client/**"
      - "test/**"
      - ".github/workflows/client.yml"
      - ".github/workflows/client-pull.yml"
      - "README.md"
      - ".sample.env"
      - "env.js"
      - "nodemon.json"

jobs:
  test_build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean Installing Dependencies
      run: npm ci
    - name: Running tests
      run: npm test
    - name: Building
      run: npm run build --if-present
