name: Backend CI & CD

on:
  push:
    branches: [ none ]
    paths-ignore:
      - "client/**"
      - "test/**"
      - ".github/workflows/client.yml"
      - ".github/workflows/client-pull.yml"
      - "README.md"
      - ".sample.env"
      - "env.js"
      - "nodemon.json"

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean Installing Dependencies
      run: npm ci
    - name: Running tests
      run: npm test
    - name: Building
      run: npm run build --if-present
    - name: Heroku Backend Deploy
      uses: akhileshns/heroku-deploy@v3.3.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL_ID}}
