name: Backend CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - "client/**"
      - "test/**"
      - ".github/workflows/client.yml"

jobs:
  test_build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
